version: "3.9"  # optional since v1.27.0
services:
  api:
    build: api
    ports:
      - "8000:8000"
#    volumes:
#      - .:/code
#      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
    ports:
      - 6379
    volumes:
      - redis:/data

volumes:
  redis: