on: [push]

name: okteto-workflow

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@1.0.0 #github action to clone this repo

    - uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - uses: okteto/namespace@master
      with:
        namespace: sunghoonism
    
    - name: "Create stack"
      uses: okteto/deploy-stack@master
      with:
        namespace: sunghoonism
        build: "true"