on: [push]

name: okteto-workflow

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:

    # - uses: okteto/login@master
    #   with:
    #     token: ${{ secrets.OKTETO_TOKEN }}
    
    # - name: "Activate Namespace"
    #   uses: okteto/namespace@master
    #   with:
    #     name: sunghoonism
    
    # - name: "Deploy application"
    #   uses: okteto/apply@master
    #   with:
    #     namespace: sunghoonism
    #     manifest: docker-compose.yml

    - uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - uses: okteto/namespace@master
    
    - name: "Create stack"
      uses: okteto/deploy-stack@master
      with:
        namespace: sunghoonism
#        build: "true"